apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbDE5OHBudC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiZEdGeWRXNHVhM1Z0WVhJdFoyOTFaRUJqWVhCblpXMXBibWt1WTI5dE9rMGhiREV3Ymw4eE1qRWgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
